FROM haskell as builder

WORKDIR /home

COPY . .

RUN ghc --make function/handler.hs -o handler

FROM alpine:3.7
RUN apk --no-cache add curl \
    && echo "Pulling watchdog binary from Github." \
    && curl -sSL https://github.com/openfaas/faas/releases/download/0.8.10/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog \
    && apk del curl --no-cache
RUN apk --no-cache add ca-certificates


WORKDIR /home/

COPY --from=builder /home/handler    .

ENV fprocess="./handler"
#
HEALTHCHECK --interval=2s CMD [ -e /tmp/.lock ] || exit 1
#
CMD ["./user/bin/fwatchdog"]