FROM flangelier/scala as builder
WORKDIR /src/handler

COPY . .

RUN scalac -d function function/handler.scala

FROM 

RUN apk --no-cache add curl \
    && echo "Pulling watchdog binary from Github." \
    && curl -sSL https://github.com/openfaas/faas/releases/download/0.8.10/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog 

FROM gcr.io/distroless/java

COPY --from=builder /src/handler /
COPY --from=builder /usr/bin/fwatchdog / 

ENV fprocess="scala handler"

HEALTHCHECK --interval=2s CMD [ -e /tmp/.lock ] || exit 1

ENTRYPOINT ["./fwatchdog"]